#!/usr/bin/env node
"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const crypto = require("node:crypto");
const root = path.resolve(__dirname, "..");
const sandbox = { console, Date, JSON, Math, URL, crypto: crypto.webcrypto, globalThis: null };
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root, "extension/shared/settings.js"), "utf8"), sandbox);
vm.runInContext(fs.readFileSync(path.join(root, "extension/shared/working_session.js"), "utf8"), sandbox);
const Settings = sandbox.FCI_SETTINGS;
const Working = sandbox.FCI_WORKING_SESSION;
const config = Settings.defaultConfig();
config.rules[0].monitor.selector = { tag: "button", kind: "id", attributeName: "", value: "composer-submit-button" };
config.rules[0].monitor.conditions = [{ enabled: true, attribute: "aria-label", operator: "contains", value: "Start Voice", caseSensitive: false }];
const profile = Settings.createProfile("AI", config, "profile-ai");
const bundle = Working.build([{ sourceTabId: 12, url: "https://ai.example.test/chat?x=1", title: "[RUNNING] ⠋ Chat", addOnActive: true, mode: "active", profileId: profile.id, profile, configMode: "profile", effectiveConfig: config }], { extensionVersion: "0.20.0", exportedAt: "2026-07-23T00:00:00.000Z" });
assert.equal(bundle.tabs.length, 1);
assert.equal(bundle.tabs[0].title, "Chat");
assert.equal(bundle.tabs[0].effectiveConfig.rules[0].monitor.selector.value, "composer-submit-button");
assert.equal(Working.parse(Working.stringify(bundle)).tabs[0].effectiveConfig.rules[0].monitor.conditions[0].value, "Start Voice");
assert.deepEqual([...Working.requiredOrigins(bundle)], ["https://ai.example.test/*"]);
assert.equal(Working.configFingerprint(config), Working.configFingerprint(Settings.normalizeConfig(config)));
assert.throws(() => Working.parse('{"format":"wrong","version":1,"tabs":[]}'));
const protocol = fs.readFileSync(path.join(root, "extension/shared/protocol.js"), "utf8");
const background = fs.readFileSync(path.join(root, "extension/background/background.js"), "utf8");
const sidebar = fs.readFileSync(path.join(root, "extension/sidebar/sidebar.js"), "utf8");
const html = fs.readFileSync(path.join(root, "extension/sidebar/sidebar.html"), "utf8");
for (const name of ["LIST_WORKING_SESSION_TABS", "EXPORT_WORKING_SESSION", "IMPORT_WORKING_SESSION"]) assert(protocol.includes(name));
assert(background.includes("async function importWorkingSession"));
assert(background.includes("before_working_session_import"));
assert(sidebar.includes("commitSelectedShellPresetDraft"));
assert(sidebar.includes("assertSavedConfig"));
assert(html.includes('id="workingSessionDialog"'));
assert(html.includes('id="saveWorkingSessionButton"'));
assert(html.includes('id="importWorkingSessionButton"'));
const manifest = JSON.parse(fs.readFileSync(path.join(root, "extension/manifest.json"), "utf8"));
assert.ok(manifest.version.split(".").map(Number).reduce((a, v, i) => a + v * [1000000, 1000, 1][i], 0) >= 20000);
assert(manifest.background.scripts.includes("shared/working_session.js"));
console.log("PASS: Phase 20 verified configuration persistence and working-session save/import contract");
