#!/usr/bin/env node
"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const crypto = require("node:crypto");

const root = path.resolve(__dirname, "..");
const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8");
const manifest = JSON.parse(read("extension/manifest.json"));

function versionAtLeast(actual, minimum) {
  const a = String(actual).split(".").map(Number);
  const b = String(minimum).split(".").map(Number);
  for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
    const av = a[i] || 0;
    const bv = b[i] || 0;
    if (av !== bv) return av > bv;
  }
  return true;
}
assert(versionAtLeast(manifest.version, "0.41.3"));

const sandbox = { console, Date, JSON, Math, URL, Uint32Array, crypto: crypto.webcrypto, globalThis: null };
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
for (const rel of [
  "extension/shared/settings.js",
  "extension/shared/command_presets.js",
  "extension/shared/local_actions.js",
  "extension/shared/prompt_templates.js",
  "extension/shared/configuration_bundle.js",
  "extension/shared/settings_snapshots.js"
]) vm.runInContext(read(rel), sandbox, { filename: rel });

const Settings = sandbox.FCI_SETTINGS;
const LocalActions = sandbox.FCI_LOCAL_ACTIONS;
const CommandPresets = sandbox.FCI_COMMAND_PRESETS;
const PromptTemplates = sandbox.FCI_PROMPT_TEMPLATES;
const Bundle = sandbox.FCI_CONFIGURATION_BUNDLE;
const Snapshots = sandbox.FCI_SETTINGS_SNAPSHOTS;
assert(Snapshots.VERSION >= 3);

const automationStore = Settings.defaultStore();
automationStore.profiles[0].name = "Automation A";
const localActionStore = LocalActions.defaultStore();
localActionStore.profiles[0].config.shell.command = "echo stable";
const commandPresetStore = CommandPresets.normalizeStore({
  revision: 4,
  presets: [{ id: "preset-stable", name: "Stable", command: "make", workingDirectory: "/tmp", updatedAt: "2026-08-07T00:00:00.000Z" }]
});
const promptTemplateStore = PromptTemplates.normalizeStore({
  customTemplates: [{ id: "custom-stable", name: "Stable prompt", prompt: "Keep this", createdAt: "2026-08-07T00:00:00.000Z", updatedAt: "2026-08-07T00:00:00.000Z" }]
});
const bundleA = Bundle.build({
  automationStore,
  localActionStore,
  commandPresetStore,
  promptTemplateStore,
  sidebarPreferences: { featurePreset: "standard", collapsedGroups: { profiles: true }, visibleFeatures: [], autoProfileByUrl: true },
  exportedAt: "2026-08-07T00:00:00.000Z"
});
const bundleB = JSON.parse(JSON.stringify(bundleA));
bundleB.exportedAt = "2099-01-01T00:00:00.000Z";
bundleB.automationStore.revision += 99;
bundleB.automationStore.profiles[0].createdAt = "2099-01-01T00:00:00.000Z";
bundleB.automationStore.profiles[0].updatedAt = "2099-01-01T00:00:01.000Z";
bundleB.automationStore.monitorProfiles[0].updatedAt = "2099-01-01T00:00:02.000Z";
bundleB.automationStore.targetProfiles[0].updatedAt = "2099-01-01T00:00:03.000Z";
bundleB.localActionStore.revision += 77;
bundleB.localActionStore.profiles[0].createdAt = "2099-01-01T00:00:04.000Z";
bundleB.localActionStore.profiles[0].updatedAt = "2099-01-01T00:00:05.000Z";
bundleB.commandPresetStore.revision += 55;
bundleB.commandPresetStore.presets[0].updatedAt = "2099-01-01T00:00:06.000Z";
bundleB.promptTemplateStore.customTemplates[0].createdAt = "2099-01-01T00:00:07.000Z";
bundleB.promptTemplateStore.customTemplates[0].updatedAt = "2099-01-01T00:00:08.000Z";

assert.equal(Bundle.fingerprint(bundleA), Bundle.fingerprint(bundleB), "revision/timestamp-only changes must not change the full-configuration fingerprint");

const changedBundle = JSON.parse(JSON.stringify(bundleB));
changedBundle.localActionStore.profiles[0].config.shell.command = "echo changed";
assert.notEqual(Bundle.fingerprint(bundleA), Bundle.fingerprint(changedBundle), "behavior-changing configuration must change the fingerprint");

const snapshotA = Snapshots.makeSnapshot(bundleA.automationStore, "test", "Older", {
  id: "snapshot-semantic-old",
  createdAt: "2026-08-07T00:00:00.000Z",
  configurationBundle: bundleA
});
const snapshotB = Snapshots.makeSnapshot(bundleB.automationStore, "test", "Newer metadata only", {
  id: "snapshot-semantic-new",
  createdAt: "2026-08-07T00:01:00.000Z",
  configurationBundle: bundleB
});
let result = Snapshots.addSnapshot({}, snapshotA);
result = Snapshots.addSnapshot(result.collection, snapshotB);
assert.equal(result.added, false, "metadata-only full-configuration snapshot must be rejected as a duplicate");
assert.equal(result.collection.snapshots.length, 1);

// Old collections may already contain multiple snapshots generated by the previous
// volatile fingerprint. Loading must compact them and keep the newest copy.
const oldCollection = {
  version: 2,
  snapshots: [
    { ...snapshotA, fingerprint: "old-volatile-a" },
    { ...snapshotB, fingerprint: "old-volatile-b" }
  ]
};
const normalized = Snapshots.normalizeCollection(oldCollection);
assert.equal(normalized.version, Snapshots.VERSION);
assert.equal(normalized.snapshots.length, 1, "existing semantic duplicates must compact on load");
assert.equal(normalized.snapshots[0].id, "snapshot-semantic-new", "newest semantic duplicate must be retained");

console.log("PASS: Phase 62 semantic full-configuration fingerprint ignores volatile metadata and compacts duplicate recovery snapshots");
